### PR TITLE
Add test suite for misc algorithmic complexity assertions

### LINKED ISSUE #36: [Tests] add tests to cover all complexity classes
These cases haven't yet been touched:

- [x] square root
- [x] quadratic
- [x] cubic
- [x] exponential
- [ ] custom

### PR DESCRIPTION
**Pull request by mossheim**
Fixes #36 

this has tests in complexities of:

- n^2 (matrix add, matrix fill)
- n^3 (naive matrix mul)
- 2^n (recursive fibonacci generator)
- sqrt(n) (simple primality test)

### CODE REVIEW

**Comment by mossheim** [comment]
haven't done one for custom complexity - do you think we need one @jsbean ?

**Comment by jsbean** [comment]
No, I think we are good w/o one. Honestly, I feel like we could remove the custom case until we run into a specific use case for it, then just bring it back from the dead when absolutely necessary.

**Review by jsbean — APPROVED** [review]

**Comment by jsbean** [comment]
Looks great!

**Comment by mossheim** [comment]
sgtm. thanks!

**Pull request merged**
